Description of display_points
Home > toolbox > visualization > display_points.m
display_points
PURPOSE
DISPLAY_POINTS displays 3D points.
SYNOPSIS
function display_points(X, varargin)
DESCRIPTION
 DISPLAY_POINTS displays 3D points.
 Input:
       X - 3d location of points (3xn) or (4xn)
 Options:
       'pixelsize', pixelsize - pixel size
       'color', color         - colors nx3 in RGB vector
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
incr_reconstruction INCR_RECONSTRUCTION performs incremental reconstruction.
demo_bundle_euclid DEMO_BUNDLE_EUCLID demonstrates the bundle adjustment.
demo_vlmvg DEMO_VLMVG demonstrates an example of 3D reconstruction pipeline.
test_bundle TEST_BUNDLE tests multiple number of tests on bundle adjustment.
test_incremental TEST_INCREMENTAL tests Euclidean reconstruction using incremental bundle adjustment.
test_mview TEST_MVIEW tests Euclidean 3D reconstruction using multi-view algorithm.