Description of bundle_euclid_nomex
Home > toolbox > bundle > bundle_euclid_nomex.m
bundle_euclid_nomex
PURPOSE
BUNDLE_EUCLID_NOMEX performs Euclidean bundle adjustment (without MEX)
SYNOPSIS
function [K_ Te_ w_ Xe_ error_] = bundle_euclid_nomex(K, Te, w, Xe, x, varargin)
DESCRIPTION
 BUNDLE_EUCLID_NOMEX  performs Euclidean bundle adjustment (without MEX)
 Input:
        K  - calibration parameters (4xm) ([fx fy cx cy]' x m-images)
        Te - translation            (3xm)
        w  - rotation               (3xm)
        Xe - 3d points              (4xn)   in homogeneous form
        x  - image points           (3xnxm) in homoegeneous form
 Options:
        'fix_structure'       - keep structure parameters fixed
        'fix_motion'          - keep motion parameters fixed
        'fix_calibration'     - keep calibration parameters fixed
        'fix_principal'       - keep principal points fixed
        'visibility', visible - set the visibility map (visible: nxm)
        'verbose'             - display verbose information
 Output:
        K_     - calibration parameters (4xm)
        Te_    - translation            (3xm)
        w_     - rotation               (3xm)
        Xe_    - 3d points              (4xn) in homogeneous form
        error_ - errors for iterations  (1x#iter)
CROSS-REFERENCE INFORMATION
This function calls:
derivative_camera DERIVATIVE_CAMERA computes the partial derivative w.r.t camera parameters.
derivative_point DERIVATIVE_POINT computes the partial derivative w.r.t point parameters.
reprojection_point REPROJECTION_POINT reprojects a point given camera and point parameters.
This function is called by:
mview_reconstruction MVIEW_RECONSTRUCTION performs multi-view reconstruction.