Description of bundle_euclid
Home > toolbox > bundle > bundle_euclid.m
bundle_euclid
PURPOSE
BUNDLE_EUCLID performs the Euclidean sparse bundle adjustment.
SYNOPSIS
function [K_ Te_ w_ Xe_ error_] = bundle_euclid(K, Te, w, Xe, x, varargin)
DESCRIPTION
 BUNDLE_EUCLID  performs the Euclidean sparse bundle adjustment.
 Input:
        K  - calibration parameters (4xm) ([fx fy cx cy]' x m-images)
        Te - translation            (3xm)
        w  - rotation               (3xm)
        Xe - 3d points              (4xn)   in homogeneous form
        x  - image points           (3xnxm) in homoegeneous form
 Options:
        'fix_structure'       - keep structure parameters fixed
        'fix_motion'          - keep motion parameters fixed
        'fix_pivot', pivot    - keep pivot motion parameters fixed
                                (pivot: 1xm logical)
        'fix_calibration'     - keep calibration parameters fixed
        'fix_principal'       - keep principal points fixed
        'visibility', visible - set the visibility map (visible: nxm)
        'verbose'             - display verbose information
 Output:
        K_     - calibration parameters (4xm)
        Te_    - translation            (3xm)
        w_     - rotation               (3xm)
        Xe_    - 3d points              (4xn) in homogeneous form
        error_ - errors for iterations  (1x#iter)
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
VLmvg VLMVG reconstructs structure and motion from feature measurements.
estimate_camera ESTIMATE_CAMERA estimates the camera parameters.
incr_reconstruction INCR_RECONSTRUCTION performs incremental reconstruction.
multi_view MULTI_VIEW performs multi-view projective reconstruction.
mview_reconstruction MVIEW_RECONSTRUCTION performs multi-view reconstruction.
demo_bundle_euclid DEMO_BUNDLE_EUCLID demonstrates the bundle adjustment.