Description of bundle_projective_nomex
Home > toolbox > bundle > bundle_projective_nomex.m
bundle_projective_nomex
PURPOSE
BUNDLE_PROJECTIVE performs the projective bundle adjustment.
SYNOPSIS
function [Pp_ Xp_ error_] = bundle_projective(Pp, Xp, x, varargin)
DESCRIPTION
 BUNDLE_PROJECTIVE performs the projective bundle adjustment.
 Input:
        Po - projection matrices (3x4xm)
        Xp - 3d points           (4xn)   in homogeneous form
        x  - image points        (3xnxm) in homogeneous form
 Options:
        'fix_structure'       - keep structure parameters fixed
        'fix_motion'          - keep motion parameters fixed
        'visibility', visible - set the visibility map (visible: nxm)
        'verbose'             - display verbose information
 Output:
        Pp_    - projection matrices   (3x4xm)
        Xp_    - 3d points             (4xn)   in homogeneous form
        error_ - errors for iterations (1x#iter)
CROSS-REFERENCE INFORMATION
This function calls:
derivative_projective_camera DERIVATIVE_PROJECTIVE_CAMERA computes the partial derivative w.r.t projective camera parameters.
derivative_projective_point DERIVATIVE_PROJECTIVE_CAMERA computes the partial derivative w.r.t projective point parameters.
reprojection_projective_point REPROJECTION_PROJECTIVE_POINT reprojects a point.
This function is called by: