Description of large_bundle_euclid
Home > toolbox > bundle > large_bundle_euclid.m
large_bundle_euclid
PURPOSE
get information
SYNOPSIS
function [K_ T_ Om_ X_ error_] = large_bundle_euclid(K, T, Om, X, x, vis)
DESCRIPTION
 get information
CROSS-REFERENCE INFORMATION
This function calls:
bundle_euclid BUNDLE_EUCLID performs the Euclidean sparse bundle adjustment.
large_bundle_euclid get information
align_scene ALIGN_SCENE aligns a scene.
This function is called by:
large_bundle_euclid get information