Description of reprojection_projective_point
Home > toolbox > bundle > reprojection_projective_point.m
reprojection_projective_point
PURPOSE
REPROJECTION_PROJECTIVE_POINT reprojects a point.
SYNOPSIS
function [x] = reprojection_projective_point(a, b)
DESCRIPTION
 REPROJECTION_PROJECTIVE_POINT reprojects a point.
 x returns 2-by-1 vector
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
bundle_projective_nomex BUNDLE_PROJECTIVE performs the projective bundle adjustment.
derivative_projective_camera DERIVATIVE_PROJECTIVE_CAMERA computes the partial derivative w.r.t projective camera parameters.
derivative_projective_point DERIVATIVE_PROJECTIVE_CAMERA computes the partial derivative w.r.t projective point parameters.