Description of align_scene
Home > toolbox > geometry > align_scene.m
align_scene
PURPOSE
ALIGN_SCENE aligns a scene.
SYNOPSIS
function [ T_ Omega_ X_ ] = align_scene(T, Omega, X, TRef, OmegaRef, XRef, ScaleOption)
DESCRIPTION
 ALIGN_SCENE aligns a scene.
 This aligns a scene represented by (T, Omega, X) to a reference frame
 (TRef, OmegaRef, XRef). The rotation and translation is aligned so that
 the first frame of T and Omega is same as the first frame of TRef and
 OmegaRef. The scale factor is aligned so that the norm of the norm of
 centroid of X is same as the norm of centroid of XRef.
 When TRef, OmegaRef and XRef are omitted, by default, reference frame
 becomes [R|T] = [I|0], and the norm of centroid of 3d points = 1.
 For example,
 >> [T_ Omega_ X_] = align_scene( T, Omega, X );
 Input:
        T        - camera translation           (3xm)
        Omega    - camera rotation              (3xm)
        X        - 3D point location            (4xn) in homogeneous form
 (Optional)
        TRef     - reference camera translation (3xm)
        OmegaRef - reference camera rotation    (3xm)
        XRef     - reference 3d point location  (4xn) in homogeneous form
        ScaleOption - set the scale factor ( 'centroid', 'translation' )
 Output:
        T_       - aligned camera translation   (3xm)
        Omega_   - aligned camera rotation      (3xm)
        X_       - aligned 3D point location    (4xn) in homogeneous form
CROSS-REFERENCE INFORMATION
This function calls:
rodrigues
This function is called by:
VLmvg VLMVG reconstructs structure and motion from feature measurements.
incr_reconstruction INCR_RECONSTRUCTION performs incremental reconstruction.
demo_bundle_euclid DEMO_BUNDLE_EUCLID demonstrates the bundle adjustment.
test_bundle TEST_BUNDLE tests multiple number of tests on bundle adjustment.
test_incremental TEST_INCREMENTAL tests Euclidean reconstruction using incremental bundle adjustment.
test_mview TEST_MVIEW tests Euclidean 3D reconstruction using multi-view algorithm.