Description of calibration_matrix
Home > toolbox > geometry > calibration_matrix.m
calibration_matrix
PURPOSE
CALIBRATION_MATRIX returns a 3x3 calibration matrix from parameters.
SYNOPSIS
function K = calibration_matrix(Kparam)
DESCRIPTION
 CALIBRATION_MATRIX returns a 3x3 calibration matrix from parameters.
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
reprojection_point REPROJECTION_POINT reprojects a point given camera and point parameters.
estimate_camera ESTIMATE_CAMERA estimates the camera parameters.
estimate_camera_DLT ESTIMATE_CAMERA_DLT estimates the camera parameters by DLT algorithm.
incr_reconstruction INCR_RECONSTRUCTION performs incremental reconstruction.
triangulation TRIANGULATION computes a 3D location of a point from more than two views.
error_reproj ERROR_REPROJ computes the reprojection error given K, w, T and X
generate_scene_and_motion GENERATE_SCENE_AND_MOTION generates a synthetic scene and camera motion.
test_mview TEST_MVIEW tests Euclidean 3D reconstruction using multi-view algorithm.
display_cameras DISPLAY_CAMERAS displays camera trajectory and view frustum.