Description of calibration_parameter
Home > toolbox > geometry > calibration_parameter.m
calibration_parameter
PURPOSE
CALIBRATION_PARAMETER returns calibration parameters (4x1) from a matrix.
SYNOPSIS
function Kparam = calibration_parameter(K)
DESCRIPTION
 CALIBRATION_PARAMETER returns calibration parameters (4x1) from a matrix.
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
VLmvg VLMVG reconstructs structure and motion from feature measurements.
estimate_camera ESTIMATE_CAMERA estimates the camera parameters.
estimate_camera_DLT ESTIMATE_CAMERA_DLT estimates the camera parameters by DLT algorithm.
incr_reconstruction INCR_RECONSTRUCTION performs incremental reconstruction.
mview_reconstruction MVIEW_RECONSTRUCTION performs multi-view reconstruction.