Description of estimate_camera_DLT
Home > toolbox > geometry > estimate_camera_DLT.m
estimate_camera_DLT
PURPOSE
ESTIMATE_CAMERA_DLT estimates the camera parameters by DLT algorithm.
SYNOPSIS
function [ K T Omega ] = estimate_camera_DLT(x, X, varargin)
DESCRIPTION
 ESTIMATE_CAMERA_DLT estimates the camera parameters by DLT algorithm.
 This performs the direct linear transform (DLT) given the set of image
 points x with respect to the corresponding 3D points X.
 x ~ K [ R | T ] X
 input:
        x = image points (3xn in image plane)
        X = 3d points (4xn)
 Options:
        'K', K - calibration parameters (4x1) or matrix (3x3)
 output:
        K     - intrinsic camera parameters              (4x1)
        T     - extrinsic camera parameter (translation) (3x1)
        Omega - extrinsic camera parameter (rotation)    (3x1)
CROSS-REFERENCE INFORMATION
This function calls:
calibration_matrix CALIBRATION_MATRIX returns a 3x3 calibration matrix from parameters.
calibration_parameter CALIBRATION_PARAMETER returns calibration parameters (4x1) from a matrix.
rq RQ performs RQ-decomposition of A.
This function is called by: