Description of estimate_camera
Home > toolbox > geometry > estimate_camera.m
estimate_camera
PURPOSE
ESTIMATE_CAMERA estimates the camera parameters.
SYNOPSIS
function [ K T Omega inlier ] = estimate_camera(x, X, varargin)
DESCRIPTION
 ESTIMATE_CAMERA estimates the camera parameters.
 This performs the direct linear transform (DLT) given the set of image
 points x with respect to the corresponding 3D points X. In addition,
 RANSAC alrogithm is used to robustly estimate the camera, followed by the
 non-linear refinement step.
 x ~ K [ R | T ] X
 input:
        x = image points (3xn in image plane)
        X = 3d points (4xn)
 Options:
        'K', K - calibration parameters (4x1) or matrix (3x3)
 output:
        K      - intrinsic camera parameters              (4x1)
        T      - extrinsic camera parameter (translation) (3x1)
        Omega  - extrinsic camera parameter (rotation)    (3x1)
        inlier - inliers among image points
CROSS-REFERENCE INFORMATION
This function calls:
bundle_euclid BUNDLE_EUCLID performs the Euclidean sparse bundle adjustment.
calibration_matrix CALIBRATION_MATRIX returns a 3x3 calibration matrix from parameters.
calibration_parameter CALIBRATION_PARAMETER returns calibration parameters (4x1) from a matrix.
This function is called by:
incr_reconstruction INCR_RECONSTRUCTION performs incremental reconstruction.