Description of incr_reconstruction
Home > toolbox > geometry > incr_reconstruction.m
incr_reconstruction
PURPOSE
INCR_RECONSTRUCTION performs incremental reconstruction.
SYNOPSIS
function [ K T Omega X goodfeat status ] = incr_reconstruction(featx, featy, varargin)
DESCRIPTION
 INCR_RECONSTRUCTION performs incremental reconstruction.
 Input:
        featx - image points x-coordinates (nxm)
        featy - image points y-coordinates (nxm)
 Options:
        'visibility', vis          - visibility map (nxm)
        'calibrated'               - indicate that camera is calibrated
        'K', K (3x3) or (4xm)      - provide a calibration matrix either
                                     calibration or guessed
        'initialized', T, Omega, X - provide initial reconstruction for
                                     the bundle adjustment
        'status', status           - provide the status of initialized
                                     frames (1xm logical)
        'X', X (4xn)               - provide initial points reconstruction
 Output:
        K     - calibration parameters     (4xm)
        T     - translation                (3xm)
        Omega - rotation                   (3xm)
        X     - 3D points                  (4xn) in homogeneous form
        goodfeat - status of image points  (nxm)
        status   - status of frames        (1xm) logical
CROSS-REFERENCE INFORMATION
This function calls:
bundle_euclid BUNDLE_EUCLID performs the Euclidean sparse bundle adjustment.
align_scene ALIGN_SCENE aligns a scene.
calibration_matrix CALIBRATION_MATRIX returns a 3x3 calibration matrix from parameters.
calibration_parameter CALIBRATION_PARAMETER returns calibration parameters (4x1) from a matrix.
estimate_camera ESTIMATE_CAMERA estimates the camera parameters.
triangulation TRIANGULATION computes a 3D location of a point from more than two views.
two_view TWO_VIEW performs a two-view projective reconstruction algorithm.
display_cameras DISPLAY_CAMERAS displays camera trajectory and view frustum.
display_points DISPLAY_POINTS displays 3D points.
This function is called by:
VLmvg VLMVG reconstructs structure and motion from feature measurements.