Description of multi_view
Home > toolbox > geometry > multi_view.m
multi_view
PURPOSE
MULTI_VIEW performs multi-view projective reconstruction.
SYNOPSIS
function [ Xp Pp x_ vis ] = multi_view(x, depth, varargin)
DESCRIPTION
 MULTI_VIEW performs multi-view projective reconstruction.
 Input:
        x     - image points (3xnxm)
        depth - initial depths of points from two-view (1xn)
 Options:
        'K', K            - calibration matrix (3x3)
        'calibrated'      - indicates the camera is calibrated
        'visibility', vis - visibility map     (nxm)
        'visualize'       - visualize intermediate reconstruction status
 Output:
        Xp  - 3d locations of points  (4xn)
        Pp  - projection matrices     (3x4xm)
        x_  - normalized image points (3xnxm)
        vis - updated visibility map  (nxm)
 NOTE: We assume tvl_hat the points in the first image are never outliers.
CROSS-REFERENCE INFORMATION
This function calls:
bundle_euclid BUNDLE_EUCLID performs the Euclidean sparse bundle adjustment.
bundle_projective BUNDLE_PROJECTIVE performs the projective bundle adjustment.
This function is called by:
mview_reconstruction MVIEW_RECONSTRUCTION performs multi-view reconstruction.