Description of mview_reconstruction
Home > toolbox > geometry > mview_reconstruction.m
mview_reconstruction
PURPOSE
MVIEW_RECONSTRUCTION performs multi-view reconstruction.
SYNOPSIS
function [ K T Omega X vis ] = mview_reconstruction(featx, featy, varargin)
DESCRIPTION
 MVIEW_RECONSTRUCTION performs multi-view reconstruction.
 Input:
        featx - image points x-coordinates (nxm)
        featy - image points y-coordinates (nxm)
 Options:
        'calibrated'               - indicate that camera is calibrated
        'K', K 3x3                 - provide a calibration matrix either
                                     calibration or guessed
        'visibility', vis          - visibility map (nxm)
        'initialized', T, Omega, X - provide initial reconstruction for
                                     the bundle adjustment
        'nomex'                    - use matlab-implementation (no mex)
                                     of the bundle adjustment
 Output:
        K     - calibration parameters     (4xm)
        T     - translation                (3xm)
        Omega - rotation                   (3xm)
        X     - 3D points                  (4xn)   in homogeneous form
        vis   - updated visibility map     (nxm)
CROSS-REFERENCE INFORMATION
This function calls:
bundle_euclid BUNDLE_EUCLID performs the Euclidean sparse bundle adjustment.
bundle_euclid_nomex BUNDLE_EUCLID_NOMEX performs Euclidean bundle adjustment (without MEX)
bundle_projective BUNDLE_PROJECTIVE performs the projective bundle adjustment.
calibration_parameter CALIBRATION_PARAMETER returns calibration parameters (4x1) from a matrix.
multi_view MULTI_VIEW performs multi-view projective reconstruction.
two_view TWO_VIEW performs a two-view projective reconstruction algorithm.
upgrade_euclid UPGRADE_EUCLID upgrades to the euclidean reconstruction
error_reproj ERROR_REPROJ computes the reprojection error given K, w, T and X
This function is called by:
VLmvg VLMVG reconstructs structure and motion from feature measurements.