Description of ransac_epipolar_constraint
Home > toolbox > geometry > ransac_epipolar_constraint.m
ransac_epipolar_constraint
PURPOSE
RANSAC_EPIPOLAR_CONSTRAINT applies the epipolar constraint using RANSAC.
SYNOPSIS
function [ inlier ] = ransac_epipolar_constraint(x1, x2, iter, thresh)
DESCRIPTION
 RANSAC_EPIPOLAR_CONSTRAINT applies the epipolar constraint using RANSAC.
 Input:
       x1, x2 = 3-by-n image point measurement for two frames
       iter   = maximum number of iteration
       thresh = threshold of the sampson distance
 Output:
       inlier = 1-by-n array indicating inliers
                (e.g. [ 0 1 1 1 1 ] --> the first element is an outlier.)
CROSS-REFERENCE INFORMATION
This function calls:
fundamental FUNDAMENTAL calculates the Fundamental matrix from point correspondences.
sampson_distance SAMPSON_DISTANCE computes the sampson distance between x1 and x2 given F
This function is called by:
remove_outliers REMOVE_OUTLIERS removes outliers among feature measurements.
generate_feature_track GENERATE_FEATURE_TRACK generates a feature track from a list of images.