Description of rodrigues
Home > toolbox > geometry > rodrigues.m
rodrigues
PURPOSE
SYNOPSIS
function [out,dout]=rodrigues(in)
DESCRIPTION
 RODRIGUES        Transform rotation matrix into rotation vector.
            Syntax:  [out,d_out_d_in]=RODRIGUES(in)
             If IN is a 3x3 rotation matrix then OUT is the
            corresponding 3x1 rotation vector
             if IN is a rotation 3-vector then OUT is the
            corresponding 3x3 rotation matrix
    d_out_d_in is the derivative of the output wrt the input
            Makes use of the following subroutines:
                -> ~/src/matlab/detensor.m
                -> ~/src/matlab/dABdA.m
                -> ~/src/matlab/dABdB.m
CROSS-REFERENCE INFORMATION
This function calls:
rodrigues
This function is called by:
align_scene ALIGN_SCENE aligns a scene.
rodrigues