Description of two_view
Home > toolbox > geometry > two_view.m
two_view
PURPOSE
TWO_VIEW performs a two-view projective reconstruction algorithm.
SYNOPSIS
function [ X lambda R T F error ] = two_view(x1, x2, varargin)
DESCRIPTION
 TWO_VIEW performs a two-view projective reconstruction algorithm.
 Input:
        x1, x2 - image points of two views (3xn)
 Options:
        'calibrated' - indicates the camera is calibrated
        'K', K       - calibration matrix (3x3)
 Output:
        X      - 3d (projective) location of poitns (4xn)
        lambda - depths of the points               (1xn)
        R      - camera rotation                    (3x3)
        T      - camera translation                 (3x1)
        F      - fundamental matrix (or essential)  (3x3)
        error  - reprojection error
CROSS-REFERENCE INFORMATION
This function calls:
fundamental FUNDAMENTAL calculates the Fundamental matrix from point correspondences.
This function is called by:
incr_reconstruction INCR_RECONSTRUCTION performs incremental reconstruction.
mview_reconstruction MVIEW_RECONSTRUCTION performs multi-view reconstruction.