Description of VLmvg
Home > toolbox > geometry > VLmvg.m
VLmvg
PURPOSE
VLMVG reconstructs structure and motion from feature measurements.
SYNOPSIS
function [ K_ T_ Omega_ X_ vis_ inlier_ ] = VLmvg(featx, featy, varargin)
DESCRIPTION
 VLMVG reconstructs structure and motion from feature measurements.
 Input:
        featx - image points x-coordinates (nxm)
        featy - image points y-coordinates (nxm)
 Options:
        'visibility', vis - visibility map     (nxm)
        'calibrated'      - indicates that the camera is calibrated
        'K', K            - camera calibraiton (3x3 or 4xm)
        'T', T            - camera translation (3xm)
        'Omega', Omega    - camera rotation    (3xm) in exponential map
        'X', X            - point location     (4xn) in homogeneous form
        'ransac'          - performs ransac for rejecting outliers
        'sampson_threshold', threshold - sampson threshold (default=1)
 Output:
        K_       - calibration parameters  (4xm)
        T_       - camera translation      (3xm)
        Omega_   - camera rotation         (3xm)
        X_       - 3D point location       (4xn) in homogeneous form
        vis_     - status of image points  (nxm)
        inlier_  - indicates inlier points (1xn)
CROSS-REFERENCE INFORMATION
This function calls:
bundle_euclid BUNDLE_EUCLID performs the Euclidean sparse bundle adjustment.
align_scene ALIGN_SCENE aligns a scene.
calibration_parameter CALIBRATION_PARAMETER returns calibration parameters (4x1) from a matrix.
incr_reconstruction INCR_RECONSTRUCTION performs incremental reconstruction.
mview_reconstruction MVIEW_RECONSTRUCTION performs multi-view reconstruction.
remove_outliers REMOVE_OUTLIERS removes outliers among feature measurements.
This function is called by:
demo_vlmvg DEMO_VLMVG demonstrates an example of 3D reconstruction pipeline.
test_incremental TEST_INCREMENTAL tests Euclidean reconstruction using incremental bundle adjustment.
test_mview TEST_MVIEW tests Euclidean 3D reconstruction using multi-view algorithm.