Description of demo_vlmvg
Home > toolbox > test > demo_vlmvg.m
demo_vlmvg
PURPOSE
DEMO_VLMVG demonstrates an example of 3D reconstruction pipeline.
SYNOPSIS
This is a script file.
DESCRIPTION
 DEMO_VLMVG demonstrates an example of 3D reconstruction pipeline.
CROSS-REFERENCE INFORMATION
This function calls:
VLmvg VLMVG reconstructs structure and motion from feature measurements.
generate_feature_track GENERATE_FEATURE_TRACK generates a feature track from a list of images.
display_cameras DISPLAY_CAMERAS displays camera trajectory and view frustum.
display_image_pair DISPLAY_IMAGE_PAIR displays a pair of image with their feature correspondences.
display_points DISPLAY_POINTS displays 3D points.
vlg_root VLG_ROOT gets VLG package root directory
This function is called by: