Description of error_reproj
Home > toolbox > test > error_reproj.m
error_reproj
PURPOSE
ERROR_REPROJ computes the reprojection error given K, w, T and X
SYNOPSIS
function [err error] = error_reproj(x, K, T, w, X, varargin)
DESCRIPTION
 ERROR_REPROJ computes the reprojection error given K, w, T and X
 Input:
       x = measurements (3-by-n-by-m)
       K = calibration matrix or parameters (3-by-3 or 3-by-3-by-m or 4-by-m )
       T = translation parameters (3-by-m)
       w = exponential map parameters (3-by-m)
       X = points in 3D (4-by-n)
 Options:
        'visibility', vis : visibility map (nxm)
 Output:
        err   = scalar value of the average reprojection error
        error = n-by-m matrix of the reprojection error
CROSS-REFERENCE INFORMATION
This function calls:
calibration_matrix CALIBRATION_MATRIX returns a 3x3 calibration matrix from parameters.
This function is called by:
mview_reconstruction MVIEW_RECONSTRUCTION performs multi-view reconstruction.
test_incremental TEST_INCREMENTAL tests Euclidean reconstruction using incremental bundle adjustment.
test_mview TEST_MVIEW tests Euclidean 3D reconstruction using multi-view algorithm.