Description of generate_feature_track
Home > toolbox > test > generate_feature_track.m
generate_feature_track
PURPOSE
GENERATE_FEATURE_TRACK generates a feature track from a list of images.
SYNOPSIS
function [ featx featy vis color ] = generate_feature_track(filelist)
DESCRIPTION
 GENERATE_FEATURE_TRACK generates a feature track from a list of images.
 Input:
        filelist - (mx1) struct array, containing filenames of images with
                   its field 'name', which is the output of 'dir' command.
 Output:
        featx - image points x-coordinates (nxm)
        featy - image points y-coordinates (nxm)
        vis   - visibility map             (nxm)
        color - color of points in RGB     (nx3)
CROSS-REFERENCE INFORMATION
This function calls:
ransac_epipolar_constraint RANSAC_EPIPOLAR_CONSTRAINT applies the epipolar constraint using RANSAC.
match_sift_unique MATCH_SIFT_UNIQUE matches two sets of SIFT descriptors.
This function is called by:
demo_vlmvg DEMO_VLMVG demonstrates an example of 3D reconstruction pipeline.