Description of generate_scene_and_motion
Home > toolbox > test > generate_scene_and_motion.m
generate_scene_and_motion
PURPOSE
GENERATE_SCENE_AND_MOTION generates a synthetic scene and camera motion.
SYNOPSIS
function [K T w X x vis] = generate_scene_and_motion(m, min_n, max_n, depth)
DESCRIPTION
 GENERATE_SCENE_AND_MOTION generates a synthetic scene and camera motion.
 Input:
       m - number of frames
       min_n - minimum number of features to track in a frame
       max_n - maximum number of features to track in a frame
       depth - mean depth of points to generate at a certain frame
 Output:
       K - camera calibration parameters (4xm)
       T - camera translation            (3xm)
       w - camera rotation               (3xm)
       X - 3d location of points         (4xn)
       x - image points                  (3xnxm)
       vis - visibility map              (nxm)
CROSS-REFERENCE INFORMATION
This function calls:
calibration_matrix CALIBRATION_MATRIX returns a 3x3 calibration matrix from parameters.
This function is called by:
demo_bundle_euclid DEMO_BUNDLE_EUCLID demonstrates the bundle adjustment.
test_incremental TEST_INCREMENTAL tests Euclidean reconstruction using incremental bundle adjustment.
test_mview TEST_MVIEW tests Euclidean 3D reconstruction using multi-view algorithm.