Description of run_sba
Home > toolbox > test > run_sba.m
run_sba
PURPOSE
RUN_SBA revokes SBA library's bundle adjustment function.
SYNOPSIS
function [ T_ w_ X_ info ] = run_sba(K, T, w, X, x, vis, method, projac_lib)
DESCRIPTION
 RUN_SBA revokes SBA library's bundle adjustment function.
 Input:
       K - camera calibration parameters (4xm)
       T - camera translation            (3xm)
       w - camera rotation               (3xm)
       X - 3d location of points         (4xn)
       x - image points                  (3xnxm)
       vis - visibility map              (nxm)
       method - method of sba optimization ('mot', 'str', or 'motstr')
       projac_lib - path of projac.dll file
                    (e.g. '/library/sba-1.4/matlab/projac.dll')
 Output:
       T_ - refined translation
       w_ - refined rotation
       X_ - refined 3d location of points
       info - information from sba()
 NOTE: This function is provided for test purpose of SBA library, which
 can be acquired from http://www.ics.forth.gr/~lourakis/sba/
CROSS-REFERENCE INFORMATION
This function calls:
iquat IQUAT computes a quaternion from a rotation matrix R
quat QUAT converts a quaternion to a rotation matrix
This function is called by:
test_bundle TEST_BUNDLE tests multiple number of tests on bundle adjustment.