Description of test_mview
Home > toolbox > test > test_mview.m
test_mview
PURPOSE
TEST_MVIEW tests Euclidean 3D reconstruction using multi-view algorithm.
SYNOPSIS
This is a script file.
DESCRIPTION
 TEST_MVIEW tests Euclidean 3D reconstruction using multi-view algorithm.
 Taehee Lee
 last update: 06/16/2008
CROSS-REFERENCE INFORMATION
This function calls:
VLmvg VLMVG reconstructs structure and motion from feature measurements.
align_scene ALIGN_SCENE aligns a scene.
calibration_matrix CALIBRATION_MATRIX returns a 3x3 calibration matrix from parameters.
error_reproj ERROR_REPROJ computes the reprojection error given K, w, T and X
generate_scene_and_motion GENERATE_SCENE_AND_MOTION generates a synthetic scene and camera motion.
display_cameras DISPLAY_CAMERAS displays camera trajectory and view frustum.
display_points DISPLAY_POINTS displays 3D points.
This function is called by: