Description of test_bundle
Home > toolbox > test > test_bundle.m
test_bundle
PURPOSE
TEST_BUNDLE tests multiple number of tests on bundle adjustment.
SYNOPSIS
This is a script file.
DESCRIPTION
 TEST_BUNDLE tests multiple number of tests on bundle adjustment.
CROSS-REFERENCE INFORMATION
This function calls:
align_scene ALIGN_SCENE aligns a scene.
demo_bundle_euclid DEMO_BUNDLE_EUCLID demonstrates the bundle adjustment.
run_sba RUN_SBA revokes SBA library's bundle adjustment function.
display_cameras DISPLAY_CAMERAS displays camera trajectory and view frustum.
display_points DISPLAY_POINTS displays 3D points.
This function is called by: